In [8]:
import numpy as np
import pickle
import torch

In [9]:
frame_dict = pickle.load(open("/home/neo/MS/espnet/egs/timit/asr1/frame_level_dict.pkl", "rb"))

In [10]:
frame_dict["MDWH0_SX125"][11]

[100, 107]

In [32]:
a = torch.rand(10,10)

In [33]:
b = torch.eye(a.size()[0])

In [34]:
b

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
a

tensor([[3.0991e-01, 3.6227e-01, 2.0067e-01, 1.0870e-01, 3.4721e-01, 9.0214e-01,
         8.6047e-01, 8.6600e-01, 3.1494e-01, 6.7489e-01],
        [3.3227e-01, 3.1642e-01, 2.3186e-01, 7.8435e-02, 5.4340e-01, 9.1907e-01,
         8.1917e-01, 3.2541e-01, 5.8246e-01, 1.3449e-01],
        [5.3914e-01, 2.3858e-02, 5.2603e-01, 2.5314e-01, 2.3888e-01, 7.8494e-01,
         5.5524e-01, 1.5121e-01, 8.9446e-01, 7.4065e-01],
        [3.0993e-01, 8.9865e-01, 5.8361e-01, 5.9294e-01, 5.5611e-01, 3.6603e-01,
         5.0303e-01, 5.8396e-01, 2.7591e-01, 9.3643e-01],
        [1.3604e-01, 3.6242e-01, 6.1609e-01, 4.5158e-01, 9.3844e-01, 7.9599e-01,
         9.7665e-01, 2.2216e-01, 5.2186e-01, 2.7676e-01],
        [7.5088e-01, 3.3000e-02, 2.1359e-01, 4.2323e-01, 5.5987e-01, 9.6019e-01,
         5.7465e-04, 9.7340e-01, 3.9094e-01, 1.6517e-01],
        [4.9910e-01, 2.7949e-01, 1.3806e-01, 5.9182e-01, 7.2237e-01, 8.6802e-01,
         6.8413e-02, 7.5675e-01, 6.8429e-01, 4.4435e-01],
        [7.7326e-01, 2.0597

In [36]:
a*b

tensor([[0.3099, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.3164, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.5260, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.5929, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.9384, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.9602, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0684, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.6205, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.7986,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.4874]])

In [39]:
a[0]

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])